# -*- coding: utf-8 -*-
'''
LANG_LIST = [{'code':'ab','name':'Abkhazian'},
{'code':'aa','name':'Afar'},
{'code':'af','name':'Afrikaans'},
{'code':'sq','name':'Albanian'},
{'code':'am','name':'Amharic'},
{'code':'ar','name':'Arabic'},
{'code':'hy','name':'Armenian'},
{'code':'as','name':'Assamese'},
{'code':'ay','name':'Aymara'},
{'code':'az','name':'Azerbaijani'},
{'code':'ba','name':'Bashkir'},
{'code':'eu','name':'Basque'},
{'code':'bn','name':'Bengali,Bangla'},
{'code':'dz','name':'Bhutani'},
{'code':'bh','name':'Bihari'},
{'code':'bi','name':'Bislama'},
{'code':'br','name':'Breton'},
{'code':'bg','name':'Bulgarian'},
{'code':'my','name':'Burmese'},
{'code':'be','name':'Byelorussian'},
{'code':'km','name':'Cambodian'},
{'code':'ca','name':'Catalan'},
{'code':'zh','name':'Chinese'},
{'code':'co','name':'Corsican'},
{'code':'hr','name':'Croatian'},
{'code':'cs','name':'Czech'},
{'code':'da','name':'Danish'},
{'code':'nl','name':'Dutch'},
{'code':'en','name':'English'},
{'code':'eo','name':'Esperanto'},
{'code':'et','name':'Estonian'},
{'code':'fo','name':'Faeroese'},
{'code':'fj','name':'Fiji'},
{'code':'fi','name':'Finnish'},
{'code':'fr','name':'French'},
{'code':'fy','name':'Frisian'},
{'code':'gd','name':'Gaelic'},
{'code':'gl','name':'Galician'},
{'code':'ka','name':'Georgian'},
{'code':'de','name':'German'},
{'code':'el','name':'Greek'},
{'code':'kl','name':'Greenlandic'},
{'code':'gn','name':'Guarani'},
{'code':'gu','name':'Gujarati'},
{'code':'ha','name':'Hausa'},
{'code':'iw','name':'Hebrew'},
{'code':'hi','name':'Hindi'},
{'code':'hu','name':'Hungarian'},
{'code':'is','name':'Icelandic'},
{'code':'in','name':'Indonesian'},
{'code':'ia','name':'Interlingua'},
{'code':'ie','name':'Interlingue'},
{'code':'ik','name':'Inupiak'},
{'code':'ga','name':'Irish'},
{'code':'it','name':'Italian'},
{'code':'ja','name':'Japanese'},
{'code':'jw','name':'Javanese'},
{'code':'kn','name':'Kannada'},
{'code':'ks','name':'Kashmiri'},
{'code':'kk','name':'Kazakh'},
{'code':'rw','name':'Kinyarwanda'},
{'code':'ky','name':'Kirghiz'},
{'code':'rn','name':'Kirundi'},
{'code':'ko','name':'Korean'},
{'code':'ku','name':'Kurdish'},
{'code':'lo','name':'Laothian'},
{'code':'la','name':'Latin'},
{'code':'lv','name':'Latvian,Lettish'},
{'code':'ln','name':'Lingala'},
{'code':'lt','name':'Lithuanian'},
{'code':'mk','name':'Macedonian'},
{'code':'mg','name':'Malagasy'},
{'code':'ms','name':'Malay'},
{'code':'ml','name':'Malayalam'},
{'code':'mt','name':'Maltese'},
{'code':'mi','name':'Maori'},
{'code':'mr','name':'Marathi'},
{'code':'mo','name':'Moldavian'},
{'code':'mn','name':'Mongolian'},
{'code':'na','name':'Nauru'},
{'code':'ne','name':'Nepali'},
{'code':'no','name':'Norwegian'},
{'code':'oc','name':'Occitan'},
{'code':'or','name':'Oriya'},
{'code':'om','name':'Oromo,Afan'},
{'code':'ps','name':'Pashto,Pushto'},
{'code':'fa','name':'Persian'},
{'code':'pl','name':'Polish'},
{'code':'pt','name':'Portuguese'},
{'code':'pa','name':'Punjabi'},
{'code':'qu','name':'Quechua'},
{'code':'rm','name':'Rhaeto-Romance'},
{'code':'ro','name':'Romanian'},
{'code':'ru','name':'Russian'},
{'code':'sm','name':'Samoan'},
{'code':'sg','name':'Sangro'},
{'code':'sa','name':'Sanskrit'},
{'code':'sr','name':'Serbian'},
{'code':'sh','name':'Serbo-Croatian'},
{'code':'st','name':'Sesotho'},
{'code':'tn','name':'Setswana'},
{'code':'sn','name':'Shona'},
{'code':'sd','name':'Sindhi'},
{'code':'si','name':'Singhalese'},
{'code':'ss','name':'Siswati'},
{'code':'sk','name':'Slovak'},
{'code':'sl','name':'Slovenian'},
{'code':'so','name':'Somali'},
{'code':'es','name':'Spanish'},
{'code':'su','name':'Sudanese'},
{'code':'sw','name':'Swahili'},
{'code':'sv','name':'Swedish'},
{'code':'tl','name':'Tagalog'},
{'code':'tg','name':'Tajik'},
{'code':'ta','name':'Tamil'},
{'code':'tt','name':'Tatar'},
{'code':'te','name':'Tegulu'},
{'code':'th','name':'Thai'},
{'code':'bo','name':'Tibetan'},
{'code':'ti','name':'Tigrinya'},
{'code':'to','name':'Tonga'},
{'code':'ts','name':'Tsonga'},
{'code':'tr','name':'Turkish'},
{'code':'tk','name':'Turkmen'},
{'code':'tw','name':'Twi'},
{'code':'uk','name':'Ukrainian'},
{'code':'ur','name':'Urdu'},
{'code':'uz','name':'Uzbek'},
{'code':'vi','name':'Vietnamese'},
{'code':'vo','name':'Volapuk'},
{'code':'cy','name':'Welsh'},
{'code':'wo','name':'Wolof'},
{'code':'xh','name':'Xhosa'},
{'code':'ji','name':'Yiddish'},
{'code':'yo','name':'Yoruba'},
{'code':'zu','name':'Zulu'}]
'''
LANG_LIST = [{'code':'en','name':'English'},{'code':'ja','name':u'日本語'}]

def default_lang(request):
    from settings import DEFAULT_LANG
    default_lang_dic = {}
    for lang in LANG_LIST:
        if lang['code'] == DEFAULT_LANG:
            default_lang_dic['code'] = lang['code']
            default_lang_dic['name'] = lang['name']
    return {'default_lang':default_lang_dic}

def lang_list(request):
    return {'lang_list':LANG_LIST}
