language: python
 
python:
  - '2.7'
 
install: 
  - 'pip install -r requirements.txt --use-mirrors'
 
before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.9.2.zip -nv
  - unzip -q google_appengine_1.9.2.zip
  - export PATH=$PATH:./google_appengine/
 
script: 'python manage.py test -v2'
